function project = reflectarrayUpgradeProject(project)
%REFLECTARRAYUPGRADEPROJECT Read older standalone reflectarray projects.
%   Version 1 stored physical millimetre spacing and a single frequency.
%   Converting those values to design wavelengths preserves the geometry.

if ~isstruct(project) || ~isscalar(project) || ...
        ~isfield(project,'formatVersion') || ...
        ~isnumeric(project.formatVersion) || ...
        ~isreal(project.formatVersion) || ...
        ~isscalar(project.formatVersion) || ...
        ~isfinite(project.formatVersion)
    error('Reflectarray:Project','Not a supported reflectarray project.');
end
if ~isfield(project,'M') || ~isfield(project,'N') || ...
        ~isnumeric(project.M) || ~isnumeric(project.N) || ...
        ~isreal(project.M) || ~isreal(project.N) || ...
        ~isscalar(project.M) || ~isscalar(project.N) || ...
        any(~isfinite([project.M project.N])) || ...
        any([project.M project.N] < 2) || ...
        any([project.M project.N] > 60) || ...
        any(mod([project.M project.N],1) ~= 0)
    error('Reflectarray:Project','Saved grid size must be 2 to 60 in each direction.');
end

switch project.formatVersion
    case 1
        required = {'dxMM','dyMM','freqGHz'};
        if ~all(isfield(project,required)) || ...
                ~isnumeric(project.freqGHz) || ...
                ~isreal(project.freqGHz) || ...
                ~isscalar(project.freqGHz) || ...
                ~isfinite(project.freqGHz) || project.freqGHz <= 0 || ...
                ~isnumeric(project.dxMM) || ~isreal(project.dxMM) || ...
                ~isscalar(project.dxMM) || ...
                ~isfinite(project.dxMM) || project.dxMM <= 0 || ...
                ~isnumeric(project.dyMM) || ~isreal(project.dyMM) || ...
                ~isscalar(project.dyMM) || ...
                ~isfinite(project.dyMM) || project.dyMM <= 0
            error('Reflectarray:Project','Old project spacing or frequency is invalid.');
        end
        lambdaMM = 299.792458/project.freqGHz;
        project.dxLambda = project.dxMM/lambdaMM;
        project.dyLambda = project.dyMM/lambdaMM;
        project.designFreqGHz = project.freqGHz;
        project.opFreqGHz = project.freqGHz;
        project.freqUnit = 'GHz';
        project.retunePhase = true;
        project = rmfield(project,required);
        project.formatVersion = 2;
    case 2
        % Already in design-wavelength units.
    case 3
        % Earlier geometry-editable format with cumulative row shifts.
    case 4
        % Alternating-row stagger format.
    case 5
        % Selectable incident-field format.
    otherwise
        error('Reflectarray:Project','Not a supported reflectarray project.');
end
if project.formatVersion == 2
    if strcmp(project.shape,'Rectangle'), project.shape = 'Custom'; end
    if ~isfield(project,'freqUnit'), project.freqUnit = 'GHz'; end
    if ~isfield(project,'angleConvention')
        project.angleConvention = 'Theta / phi';
    end
    if ~isfield(project,'manualEnabled'), project.manualEnabled = false; end
    if ~isfield(project,'manualPhaseDeg'), project.manualPhaseDeg = []; end
    if ~isfield(project,'selected'), project.selected = [1 1]; end
    project.gridAngleDeg = 90;
    project.rowStaggerLambda = 0;
    project.staggerAngleDeg = 0;
    project.activeMask = [];
    project.xOffsetLambda = zeros(project.M,project.N);
    project.yOffsetLambda = zeros(project.M,project.N);
    project.selectedCells = project.selected;
    project.formatVersion = 3;
end
if project.formatVersion == 3
    required = {'rowStaggerLambda','staggerAngleDeg', ...
        'xOffsetLambda','yOffsetLambda','dyLambda'};
    if ~all(isfield(project,required)) || ...
            ~isnumeric(project.rowStaggerLambda) || ...
            ~isreal(project.rowStaggerLambda) || ...
            ~isscalar(project.rowStaggerLambda) || ...
            ~isnumeric(project.staggerAngleDeg) || ...
            ~isreal(project.staggerAngleDeg) || ...
            ~isscalar(project.staggerAngleDeg) || ...
            ~isnumeric(project.dyLambda) || ...
            ~isreal(project.dyLambda) || ...
            ~isscalar(project.dyLambda) || ...
            ~isnumeric(project.xOffsetLambda) || ...
            ~isnumeric(project.yOffsetLambda) || ...
            ~isreal(project.xOffsetLambda) || ...
            ~isreal(project.yOffsetLambda) || ...
            ~isequal(size(project.xOffsetLambda),[project.M project.N]) || ...
            ~isequal(size(project.yOffsetLambda),[project.M project.N]) || ...
            any(~isfinite([project.rowStaggerLambda ...
            project.staggerAngleDeg project.dyLambda])) || ...
            project.dyLambda <= 0 || ...
            any(~isfinite(project.xOffsetLambda(:))) || ...
            any(~isfinite(project.yOffsetLambda(:)))
        error('Reflectarray:Project','Old lattice settings are invalid.');
    end
    % Keep every v3 physical cell at exactly the same coordinate while
    % switching the control to alternating-row stagger. The difference
    % between the old and new lattice is folded into per-cell offsets.
    oldRows = repmat((1:project.M).'-(project.M+1)/2,1,project.N);
    alternateRows = repmat(mod((1:project.M).',2) == 0,1,project.N);
    oldShift = oldRows*project.rowStaggerLambda;
    project.xOffsetLambda = project.xOffsetLambda + ...
        oldShift*cosd(project.staggerAngleDeg) - ...
        alternateRows*project.rowStaggerLambda;
    project.yOffsetLambda = project.yOffsetLambda + ...
        oldShift*sind(project.staggerAngleDeg);
    project.staggerAngleDeg = atan2d( ...
        project.rowStaggerLambda,project.dyLambda);
    project.formatVersion = 4;
end
if project.formatVersion == 4
    project.illuminationMode = 'Horn';
    project.incidentThetaDeg = 0;
    project.incidentPhiDeg = 0;
    project.formatVersion = 5;
end
% Older projects stored a drawing-only cell angle. It had no
% effect on the scalar pattern and is no longer part of the model.
if isfield(project,'rotationDeg')
    project = rmfield(project,'rotationDeg');
end
end
