function A = reflectarrayValidateProject(P)
%REFLECTARRAYVALIDATEPROJECT Check saved values against the actual UI limits.
%   Validate the entire project before any live application state changes.

if ~isstruct(P) || ~isscalar(P) || ~isfield(P,'formatVersion') || ...
        ~isequal(P.formatVersion,5)
    error('Reflectarray:Project','Not a supported reflectarray project.');
end
checkRange(P,'M',2,60,true);
checkRange(P,'N',2,60,true);
checkRange(P,'dxLambda',0.01,10,false);
checkRange(P,'dyLambda',0.01,10,false);
checkRange(P,'designFreqGHz',0.01,300,false);
checkRange(P,'opFreqGHz',0.01,300,false);
checkRange(P,'feedQ',0,30,false);
checkRange(P,'incidentThetaDeg',0,85,false);
checkRange(P,'incidentPhiDeg',0,360,false);
checkRange(P,'beamThetaDeg',0,90,false);
checkRange(P,'beamPhiDeg',0,360,false);
checkRange(P,'gridAngleDeg',1,179,false);
checkRange(P,'rowStaggerLambda',-10,10,false);
checkRange(P,'staggerAngleDeg',-89.99,89.99,false);
checkChoice(P,'shape', ...
    {'Custom','Diamond','Hexagon','Octagon','Circle','Ellipse'});
checkChoice(P,'taper',{'None','Hann (ideal amplitude)'});
checkChoice(P,'illuminationMode',{'Horn','Plane wave'});
checkChoice(P,'freqUnit',{'GHz','MHz'});
checkChoice(P,'angleConvention', ...
    {'Theta / phi','Elevation / azimuth'});
checkBoolean(P,'retunePhase');
checkBoolean(P,'manualEnabled');
if ~isfield(P,'feedMM') || ~isnumeric(P.feedMM) || ...
        ~isreal(P.feedMM) || ...
        ~isequal(size(P.feedMM),[1 3]) || ...
        any(~isfinite(P.feedMM)) || ...
        any(P.feedMM(1:2) < -10000) || ...
        any(P.feedMM(1:2) > 10000) || ...
        P.feedMM(3) < 1 || P.feedMM(3) > 10000
    error('Reflectarray:Project','Saved horn location is outside the control limits.');
end
if abs(P.staggerAngleDeg-atan2d(P.rowStaggerLambda,P.dyLambda)) > 1e-8
    error('Reflectarray:Project','Saved stagger angle does not match row stagger.');
end
if ~isfield(P,'selected') || ~isnumeric(P.selected) || ...
        ~isreal(P.selected) || ...
        ~(isequal(size(P.selected),[1 2]) || ...
        isequal(size(P.selected),[0 2])) || ...
        any(~isfinite(P.selected(:))) || ...
        any(mod(P.selected(:),1) ~= 0) || ...
        (~isempty(P.selected) && ...
        (P.selected(1) < 1 || P.selected(1) > P.M || ...
        P.selected(2) < 1 || P.selected(2) > P.N))
    error('Reflectarray:Project','Saved selected cell is invalid.');
end
if ~isfield(P,'selectedCells') || ~isnumeric(P.selectedCells) || ...
        ~isreal(P.selectedCells) || ...
        size(P.selectedCells,2) ~= 2 || ...
        any(~isfinite(P.selectedCells(:))) || ...
        any(mod(P.selectedCells(:),1) ~= 0) || ...
        any(P.selectedCells(:,1) < 1) || ...
        any(P.selectedCells(:,1) > P.M) || ...
        any(P.selectedCells(:,2) < 1) || ...
        any(P.selectedCells(:,2) > P.N)
    error('Reflectarray:Project','Saved cell selection is invalid.');
end
if isempty(P.selected) ~= isempty(P.selectedCells) || ...
        (~isempty(P.selected) && ...
        ~any(all(P.selectedCells == P.selected,2)))
    error('Reflectarray:Project','Saved cell selection is inconsistent.');
end
if ~isfield(P,'manualPhaseDeg') || ...
        ~(isempty(P.manualPhaseDeg) && ~P.manualEnabled) && ...
        (~isnumeric(P.manualPhaseDeg) || ...
        ~isreal(P.manualPhaseDeg) || ...
        ~isequal(size(P.manualPhaseDeg),[P.M P.N]) || ...
        any(~isfinite(P.manualPhaseDeg(:))) || ...
        (P.manualEnabled && any(abs(P.manualPhaseDeg(:)) > 36000)))
    error('Reflectarray:Project','Saved manual phase grid is invalid.');
end
% Also validates masks, per-cell offsets, illumination and model settings.
A = reflectarrayAperture(P);
end

function checkRange(P,name,lo,hi,integerOnly)
if ~isfield(P,name) || ~isnumeric(P.(name)) || ...
        ~isreal(P.(name)) || ...
        ~isscalar(P.(name)) || ~isfinite(P.(name)) || ...
        P.(name) < lo || P.(name) > hi || ...
        (integerOnly && mod(P.(name),1) ~= 0)
    error('Reflectarray:Project','Saved %s is outside the control limits.',name);
end
end

function checkChoice(P,name,choices)
if ~isfield(P,name) || ...
        ~(ischar(P.(name)) || (isstring(P.(name)) && isscalar(P.(name)))) || ...
        ~any(strcmp(P.(name),choices))
    error('Reflectarray:Project','Saved %s is invalid.',name);
end
end

function checkBoolean(P,name)
if ~isfield(P,name) || ...
        ~(islogical(P.(name)) || isnumeric(P.(name))) || ...
        ~isreal(P.(name)) || ...
        ~isscalar(P.(name)) || ~ismember(P.(name),[0 1])
    error('Reflectarray:Project','Saved %s must be on or off.',name);
end
end
