function testReflectarrayDesigner
% Numerical invariants and a focused standalone UI smoke test.
here = fileparts(mfilename('fullpath'));
addpath(here,'-begin');
P = struct('M',8,'N',8,'dxLambda',0.5,'dyLambda',0.5, ...
    'designFreqGHz',10,'opFreqGHz',10,'retunePhase',true, ...
    'feedMM',[0 0 150],'feedQ',4,'beamThetaDeg',0, ...
    'beamPhiDeg',0,'shape','Rectangle','taper','None');
A = reflectarrayAperture(P);
assert(abs(A.dxMM-0.5*299.792458/10) < 1e-12 && ...
    abs(A.dyMM-0.5*299.792458/10) < 1e-12, ...
    'Physical spacing must be set by design wavelength.');
E = reflectarrayField(A,A.idealPhaseDeg,0,0);
assert(abs(abs(E)-1) < 1e-12, ...
    'Ideal broadside reflection phases must cancel every feed path.');
complexPhase = complex(A.idealPhaseDeg,ones(size(A.idealPhaseDeg)));
assert(rejectsCalculation(@()reflectarrayField(A,complexPhase,0,0)) && ...
    rejectsCalculation(@()reflectarrayDirectivity(A,complexPhase)) && ...
    rejectsCalculation(@()reflectarrayField(A,A.idealPhaseDeg,1i,0)) && ...
    rejectsCalculation(@()reflectarrayPhaseMaps(A,complexPhase,P,41)) && ...
    rejectsCalculation(@()reflectarrayPhaseMaps(A,A.idealPhaseDeg,P,41+1i)) && ...
    rejectsCalculation(@()reflectarrayWriteCells(A,complexPhase,P, ...
        [tempname '.csv'],'csv')), ...
    'Public calculations and exports must reject complex phases or directions.');
Q = P;
Q.M = 2; Q.N = 2; Q.feedMM = [0 0 1e6]; Q.feedQ = 0;
Q.shape = 'Custom';
B = reflectarrayAperture(Q);
testTheta = 37; testPhi = 33;
analytic = abs(cos(pi*Q.dxLambda*sind(testTheta)*cosd(testPhi))* ...
    cos(pi*Q.dyLambda*sind(testTheta)*sind(testPhi)));
assert(abs(abs(reflectarrayField(B,B.idealPhaseDeg, ...
    testTheta,testPhi))-analytic) < 1e-6, ...
    'Off-axis field must match the analytic 2-by-2 array factor.');
square = P;
square.M = 20; square.N = 20; square.shape = 'Custom';
squareAperture = reflectarrayAperture(square);
squareAperture.amplitude(:) = 1;
cutAngles = [0 2 5 8 12];
alpha = pi*square.dxLambda*sind(cutAngles);
expectedSquare = abs(sin(square.N*alpha)./(square.N*sin(alpha)));
expectedSquare(1) = 1;
actualSquare = abs(reflectarrayField(squareAperture, ...
    squareAperture.referencePhaseDeg,cutAngles,zeros(size(cutAngles))));
assert(max(abs(actualSquare-expectedSquare)) < 1e-11, ...
    'A uniformly lit 20-by-20 reflectarray must reproduce the phased-array factor.');
plane = square;
plane.illuminationMode = 'Plane wave';
plane.incidentThetaDeg = 0; plane.incidentPhiDeg = 0;
planeA = reflectarrayAperture(plane);
planeField = abs(reflectarrayField(planeA,planeA.referencePhaseDeg, ...
    cutAngles,zeros(size(cutAngles))));
assert(all(planeA.amplitude(planeA.active) == 1) && ...
    max(abs(planeField-expectedSquare)) < 1e-11 && ...
    all(planeA.referencePhaseDeg(planeA.active) == 0), ...
    'Normal plane-wave illumination must give a uniform broadside aperture.');
sweepPlane = plane;
sweepPlane.beamThetaDeg = 30; sweepPlane.beamPhiDeg = 0;
sweepA = reflectarrayAperture(sweepPlane);
sweep = reflectarrayFrequencySweep(sweepPlane,sweepA.referencePhaseDeg, ...
    [8 10 12]);
expectedTheta = asind(10./[8 10 12]*sind(30));
assert(max(abs(sweep.peakThetaDeg-expectedTheta)) <= 0.5 && ...
    all(sweep.peakDbi >= sweep.targetDbi-1e-10) && ...
    sweep.pointingErrorDeg(2) < 0.3, ...
    'A fixed plane-wave phase map must show the predicted beam squint.');
centerD = reflectarrayDirectivity(sweepA,sweepA.referencePhaseDeg);
assert(abs(sweep.targetDbi(2)-10*log10(centerD.factor)) < 1e-10, ...
    'Sweep directivity at the phase-setting frequency must match the model.');
oneCell = plane;
oneCell.M = 2; oneCell.N = 2;
oneCell.activeMask = logical([1 0;0 0]);
oneA = reflectarrayAperture(oneCell);
oneD = reflectarrayDirectivity(oneA,oneA.referencePhaseDeg);
assert(abs(10*log10(oneD.factor)-10*log10(2)) < 1e-10, ...
    'A single upper-hemisphere scalar cell must have 3.01 dBi directivity.');
twoByTwo = rmfield(oneCell,'activeMask');
twoA = reflectarrayAperture(twoByTwo);
twoD = reflectarrayDirectivity(twoA,twoA.referencePhaseDeg);
diagonalKernel = sin(pi*sqrt(2))/(pi*sqrt(2));
expectedTwoD = 8/(1+diagonalKernel);
assert(abs(twoD.factor-expectedTwoD) < 1e-10, ...
    'The 2-by-2 directivity must match the exact cell-pair integral.');
overlap = twoByTwo;
overlap.activeMask = logical([1 1;0 0]);
overlap.xOffsetLambda = [0 -0.5;0 0];
overlap.yOffsetLambda = zeros(2);
overlapA = reflectarrayAperture(overlap);
opposing = overlapA.referencePhaseDeg;
opposing(1,2) = mod(opposing(1,1)+180,360);
overlapD = reflectarrayDirectivity(overlapA,opposing);
assert(isnan(overlapD.factor), ...
    'Perfectly cancelling coincident cells have undefined directivity.');
plane.incidentThetaDeg = 25; plane.incidentPhiDeg = 40;
plane.beamThetaDeg = 30; plane.beamPhiDeg = 115;
planeA = reflectarrayAperture(plane);
ui = [sind(25)*cosd(40) sind(25)*sind(40)];
uo = [sind(30)*cosd(115) sind(30)*sind(115)];
expectedPlanePhase = -planeA.k*(planeA.X*(ui(1)+uo(1)) + ...
    planeA.Y*(ui(2)+uo(2)));
assert(max(abs(exp(1i*deg2rad(planeA.idealPhaseDeg(:)))- ...
    exp(1i*expectedPlanePhase(:)))) < 1e-12 && ...
    abs(reflectarrayField(planeA,planeA.idealPhaseDeg,30,115)-1) < 1e-12, ...
    'Oblique plane-wave phases must focus coherently at the requested beam.');
planeMaps = reflectarrayPhaseMaps(planeA,planeA.referencePhaseDeg,plane,41);
assert(max(abs(exp(1i*deg2rad(planeMaps.spatialDeg(:)))- ...
    exp(1i*planeA.k*(planeA.X(:)*ui(1)+planeA.Y(:)*ui(2))))) < 1e-12, ...
    'Plane-wave phase map must show the incident linear phase gradient.');
planeCsv = [tempname '.csv'];
planeCleanup = onCleanup(@()deleteExportFiles(planeCsv,''));
reflectarrayWriteCells(planeA,planeA.referencePhaseDeg,plane,planeCsv,'csv');
planeExport = readtable(planeCsv);
expectedIncident = mod(rad2deg(planeA.k*(planeExport.x_mm*ui(1)+ ...
    planeExport.y_mm*ui(2))),360);
assert(max(abs(exp(1i*deg2rad(planeExport.incident_phase_deg))- ...
    exp(1i*deg2rad(expectedIncident)))) < 1e-11, ...
    'CSV incident phase must follow the selected plane-wave model.');
clear planeCleanup;
assert(max(abs(A.idealPhaseDeg-rot90(A.idealPhaseDeg,2)),[],'all') < 1e-10, ...
    'Centered-feed broadside map should have central symmetry.');

P.feedMM = [-35 20 150];
P.beamThetaDeg = 25; P.beamPhiDeg = 40;
A = reflectarrayAperture(P);
E = reflectarrayField(A,A.idealPhaseDeg,25,40);
assert(abs(E-1) < 1e-12, ...
    'Offset-feed steering must be coherent at the commanded direction.');
maps = reflectarrayPhaseMaps(A,A.referencePhaseDeg,P,51);
combined = exp(1i*deg2rad(-maps.spatialDeg+maps.progressiveDeg));
assert(max(abs(combined(:)-exp(1i*deg2rad(maps.reflectionDeg(:))))) < 1e-12, ...
    'Spatial delay and progressive phase must reconstruct the cell reflection phase.');
assert(isequal(size(maps.continuousDeg),[51 51]) && ...
    all(isfinite(maps.continuousDeg(:))), ...
    'The ideal continuous phase view must cover the whole nominal aperture.');
cellSamples = reflectarrayPhaseMaps(A,A.referencePhaseDeg,P,17);
continuousAtCells = cellSamples.continuousDeg(2:2:16,2:2:16);
assert(max(abs(exp(1i*deg2rad(continuousAtCells(:)))- ...
    exp(1i*deg2rad(A.referencePhaseDeg(:))))) < 1e-12, ...
    'The continuous phase law must equal the discrete law at cell centres.');
Rcheck = norm([A.X(3,5)-P.feedMM(1), ...
    A.Y(3,5)-P.feedMM(2),-P.feedMM(3)]);
kcheck = 2*pi*P.designFreqGHz/299.792458;
uxcheck = sind(P.beamThetaDeg)*cosd(P.beamPhiDeg);
uycheck = sind(P.beamThetaDeg)*sind(P.beamPhiDeg);
expectedPhase = kcheck*(Rcheck-A.X(3,5)*uxcheck-A.Y(3,5)*uycheck);
assert(abs(exp(1i*deg2rad(maps.reflectionDeg(3,5)))- ...
    exp(1i*expectedPhase)) < 1e-12, ...
    'An offset-feed, off-axis cell must match the published phase law.');
shifted = mod(A.idealPhaseDeg+73,360);
assert(abs(abs(reflectarrayField(A,shifted,25,40))-abs(E)) < 1e-12, ...
    'A common cell-phase offset must not alter the power pattern.');
changed = A.idealPhaseDeg;
changed(4,4) = mod(changed(4,4)+180,360);
assert(abs(reflectarrayField(A,changed,25,40)) < abs(E), ...
    'A wrong cell phase must reduce the target field.');
pairDirectivity = reflectarrayDirectivity(A,changed);
thetaGrid = 0:0.5:90;
phiGrid = 0:2:358;
[thetaMesh,phiMesh] = meshgrid(thetaGrid,phiGrid);
integrationField = reflectarrayField(A,changed,thetaMesh,phiMesh);
integratedPower = trapz(deg2rad(thetaGrid), ...
    sum(abs(integrationField).^2.*sind(thetaMesh),1)*deg2rad(2));
quadratureDirectivity = 4*pi/integratedPower;
assert(abs(10*log10(pairDirectivity.factor)- ...
    10*log10(quadratureDirectivity)) < 0.01, ...
    'Horn-fed, manually edited directivity must match angular integration.');

designX = A.X;
designPhase = A.referencePhaseDeg;
P.opFreqGHz = 12;
A = reflectarrayAperture(P);
assert(isequal(A.X,designX) && ...
    abs(abs(reflectarrayField(A,A.referencePhaseDeg,25,40))-1) < 1e-12, ...
    'Operating frequency must change propagation without moving cells.');
P.retunePhase = false;
A = reflectarrayAperture(P);
assert(isequal(A.referencePhaseDeg,designPhase) && ...
    abs(reflectarrayField(A,A.referencePhaseDeg,25,40)) < ...
    abs(reflectarrayField(A,A.idealPhaseDeg,25,40)), ...
    'Fixed design-frequency phases must show operating-frequency loss.');
P.opFreqGHz = 10; P.retunePhase = true;

oldProject = rmfield(P,{'dxLambda','dyLambda','designFreqGHz', ...
    'opFreqGHz','retunePhase'});
oldProject.dxMM = 15; oldProject.dyMM = 15;
oldProject.freqGHz = 10; oldProject.formatVersion = 1;
upgraded = reflectarrayUpgradeProject(oldProject);
assert(upgraded.formatVersion == 5 && ...
    strcmp(upgraded.illuminationMode,'Horn') && ...
    abs(upgraded.dxLambda*299.792458/upgraded.designFreqGHz-15) < 1e-12 && ...
    abs(upgraded.dyLambda*299.792458/upgraded.designFreqGHz-15) < 1e-12, ...
    'Opening an old project must preserve its physical cell spacing.');
reflectarrayValidateProject(upgraded);
legacy = upgraded;
legacy.rotationDeg = zeros(legacy.M,legacy.N);
legacy = reflectarrayUpgradeProject(legacy);
assert(~isfield(legacy,'rotationDeg'), ...
    'Opening an older project must discard drawing-only cell rotation.');
oldStagger = upgraded;
oldStagger.shape = 'Custom';
oldStagger.gridAngleDeg = 75;
oldStagger.rowStaggerLambda = -0.2;
oldStagger.staggerAngleDeg = 25;
oldStagger.xOffsetLambda(2,3) = 0.3;
oldStagger.yOffsetLambda(4,5) = -0.15;
oldStagger.formatVersion = 3;
oldRows = repmat((1:oldStagger.M).'-(oldStagger.M+1)/2,1,oldStagger.N);
migrated = reflectarrayUpgradeProject(oldStagger);
B = reflectarrayAperture(migrated);
oldLambdaMM = 299.792458/oldStagger.designFreqGHz;
oldPositionsX = B.baseX+B.baseY*cosd(75) + ...
    oldRows*oldStagger.rowStaggerLambda*oldLambdaMM*cosd(25) + ...
    oldStagger.xOffsetLambda*oldLambdaMM;
oldPositionsY = B.baseY*sind(75) + ...
    oldRows*oldStagger.rowStaggerLambda*oldLambdaMM*sind(25) + ...
    oldStagger.yOffsetLambda*oldLambdaMM;
assert(migrated.formatVersion == 5 && ...
    max(abs(B.X-oldPositionsX),[],'all') < 1e-10 && ...
    max(abs(B.Y-oldPositionsY),[],'all') < 1e-10, ...
    'Old staggered projects must keep every physical cell position.');

V = migrated;
V.freqUnit = 'GHz'; V.angleConvention = 'Theta / phi';
V.manualEnabled = false; V.manualPhaseDeg = [];
V.selected = [1 1]; V.selectedCells = [1 1];
reflectarrayValidateProject(V);
unselected = V;
unselected.selected = zeros(0,2);
unselected.selectedCells = zeros(0,2);
reflectarrayValidateProject(unselected);
badSelection = unselected;
badSelection.selectedCells = [1 1];
assert(rejectsProject(badSelection), ...
    'Saved cell selection must have a matching primary cell.');
bad = V; bad.M = 1;
assert(rejectsProject(bad),'Projects outside row-spinner bounds must be rejected.');
bad = V; bad.dxLambda = 11;
assert(rejectsProject(bad),'Projects outside spacing bounds must be rejected.');
bad = V; bad.feedMM(3) = 0;
assert(rejectsProject(bad),'Invalid feed locations must be rejected.');
bad = V; bad.incidentThetaDeg = 90;
assert(rejectsProject(bad),'Invalid plane-wave incidence must be rejected.');
bad = V; bad.gridAngleDeg = 180;
assert(rejectsProject(bad),'Projects outside lattice bounds must be rejected.');
bad = V; bad.manualEnabled = true; bad.manualPhaseDeg = NaN(V.M,V.N);
assert(rejectsProject(bad),'Nonfinite manual phases must be rejected.');
bad = V; bad.manualEnabled = true;
bad.manualPhaseDeg = 40000*ones(V.M,V.N);
assert(rejectsProject(bad), ...
    'Saved manual phases beyond the cell-spinner limits must be rejected.');
bad = V; bad.xOffsetLambda(1,1) = 1i;
assert(rejectsProject(bad),'Complex cell offsets must be rejected.');

P.taper = 'Hann (ideal amplitude)';
B = reflectarrayAperture(P);
assert(B.amplitude(1,1) < B.amplitude(4,4), ...
    'Hann taper must reduce edge-cell amplitude.');
P.shape = 'Circle';
B = reflectarrayAperture(P);
assert(nnz(B.active) < P.M*P.N && nnz(B.active) > 0, ...
    'Circular mask must retain only in-aperture cells.');
P.shape = 'Ellipse';
C = reflectarrayAperture(P);
assert(~isequal(B.active,C.active), ...
    'Ellipse must be distinct from Circle on a square lattice.');
P.shape = 'Custom';
P.gridAngleDeg = 90;
P.rowStaggerLambda = 0.2;
P.staggerAngleDeg = atan2d(P.rowStaggerLambda,P.dyLambda);
P.xOffsetLambda = zeros(P.M,P.N);
P.yOffsetLambda = zeros(P.M,P.N);
C = reflectarrayAperture(P);
rowShift = (C.X(:,1)-C.baseX(:,1))/C.designLambdaMM;
assert(max(abs(rowShift(1:2:end))) < 1e-12 && ...
    max(abs(rowShift(2:2:end)-0.2)) < 1e-12, ...
    'Row stagger must shift alternate rows only.');
P.gridAngleDeg = 75;
P.rowStaggerLambda = 0.2;
P.staggerAngleDeg = atan2d(P.rowStaggerLambda,P.dyLambda);
P.xOffsetLambda = zeros(P.M,P.N);
P.yOffsetLambda = zeros(P.M,P.N);
P.xOffsetLambda(4,4) = 0.3;
C = reflectarrayAperture(P);
assert(abs(abs(reflectarrayField(C,C.idealPhaseDeg, ...
    P.beamThetaDeg,P.beamPhiDeg))-1) < 1e-12, ...
    'Skewed and moved cells must still focus at the requested beam.');
csvPath = [tempname '.csv']; tsvPath = [tempname '.tsv'];
filesCleanup = onCleanup(@()deleteExportFiles(csvPath,tsvPath));
assert(reflectarrayWriteCells(C,C.referencePhaseDeg,P,csvPath,'csv') == 64 && ...
    reflectarrayWriteCells(C,C.referencePhaseDeg,P,tsvPath,'tsv') == 64, ...
    'Both export formats must include every active cell.');
exported = readtable(csvPath);
assert(~ismember('physical_rotation_deg',exported.Properties.VariableNames), ...
    'CSV should contain only modelled cell properties.');
expected = mod(exported.reflection_phase_deg+exported.incident_phase_deg,360);
assert(max(abs(expected-exported.equivalent_excitation_phase_deg)) < 1e-9 && ...
    abs(exported.x_mm(28)-C.X(4,4)) < 1e-9 && ...
    contains(fileread(tsvPath),'NOT a feed or physical reflector model'), ...
    'CSV and TSV must describe equivalent aperture excitation correctly.');
P.manualEnabled = true;
reflectarrayWriteCells(C,C.referencePhaseDeg,P,csvPath,'csv');
reflectarrayWriteCells(C,C.referencePhaseDeg,P,tsvPath,'tsv');
manualExport = readtable(csvPath);
assert(all(isnan(manualExport.phase_reference_GHz)) && ...
    contains(fileread(tsvPath),'manual / unspecified'), ...
    'Manual-phase exports must not claim a synthesis frequency.');
P.manualEnabled = false;
clear filesCleanup;
P.activeMask = false(P.M,P.N);
C = reflectarrayAperture(P);
assert(~any(C.active(:)) && reflectarrayField(C,C.referencePhaseDeg,0,0) == 0, ...
    'An empty surface must calculate as zero field.');
assert(isnan(reflectarrayDirectivity(C,C.referencePhaseDeg).factor), ...
    'An empty surface has undefined directivity.');
Q = P;
Q.feedMM = [1000 0 1];
Q.xOffsetLambda = 100*ones(Q.M,Q.N);
Q.yOffsetLambda = zeros(Q.M,Q.N);
B = reflectarrayAperture(Q);
assert(all(isfinite(B.illumination(:))) && ...
    all(B.illumination(:) == 0), ...
    'An empty, unilluminated surface must not contain NaN illumination.');

Q = P;
Q.M = 60; Q.N = 60;
Q.shape = 'Custom'; Q.activeMask = [];
Q.xOffsetLambda = zeros(60); Q.yOffsetLambda = zeros(60);
Q.gridAngleDeg = 90; Q.rowStaggerLambda = 0;
Q.staggerAngleDeg = 0; Q.feedMM = [0 0 1e6];
Q.feedQ = 0; Q.beamThetaDeg = 30; Q.beamPhiDeg = 2;
B = reflectarrayAperture(Q);
surface = reflectarrayPattern3D(B,B.idealPhaseDeg,30,2);
thetaIndex = find(surface.thetaDeg == 30,1);
phiIndex = find(surface.phiDeg == 2,1);
oppositePhiIndex = find(surface.phiDeg == 182,1);
assert(~isempty(thetaIndex) && ~isempty(phiIndex) && ...
    ~isempty(oppositePhiIndex) && ...
    surface.fieldMagnitude(phiIndex,thetaIndex) > 0.99 && ...
    max(surface.fieldMagnitude(:)) >= ...
    abs(reflectarrayField(B,B.idealPhaseDeg,30,2))-1e-12, ...
    'The 3D pattern must sample the target and both elevation half-planes.');
assert(max(abs(surface.fieldMagnitude(oppositePhiIndex,:)- ...
    abs(reflectarrayField(B,B.idealPhaseDeg,surface.thetaDeg, ...
    182*ones(size(surface.thetaDeg)))))) < 1e-12, ...
    'The 3D opposite half-plane must agree with the 2D elevation cut.');
Q.dxLambda = 10; Q.dyLambda = 10;
B = reflectarrayAperture(Q);
surface = reflectarrayPattern3D(B,B.idealPhaseDeg,30,2);
nearTheta = surface.thetaDeg(abs(surface.thetaDeg-30) < 0.2);
nearPhi = surface.phiDeg(abs(surface.phiDeg-2) < 0.4);
assert(numel(nearTheta) >= 11 && numel(nearPhi) >= 11, ...
    '3D target sampling must tighten for a large electrical aperture.');

reflectarrayDesigner;
f = findall(0,'Type','figure','Tag','reflectarrayDesigner');
assert(isscalar(f),'Standalone designer did not open.');
cleanup = onCleanup(@()delete(f));
startupLabel = findall(f,'Tag','reflectarraySelectedCellLabel');
startupOutline = findall(f,'Tag','reflectarraySelectedGeometryCell');
startupPhase = findall(f,'Tag','reflectarrayCellPhase');
startupMove = findall(f,'Tag','reflectarrayCellAction1');
startupDelete = findall(f,'Tag','reflectarrayCellAction3');
assert(strcmp(startupLabel.Text,'No cell selected') && ...
    strcmp(startupOutline.Visible,'off') && ...
    strcmp(startupPhase.Enable,'off') && ...
    strcmp(startupMove.Enable,'off') && ...
    strcmp(startupDelete.Enable,'off'), ...
    'The designer must open without a selected cell.');
startupCells = findall(f,'Tag','reflectarrayCells');
startupCells.ButtonDownFcn(startupCells, ...
    struct('IntersectionPoint',[0 0 0]));
assert(contains(startupLabel.Text,'Cell (') && ...
    strcmp(startupOutline.Visible,'on') && ...
    strcmp(startupPhase.Enable,'on'), ...
    'Clicking a cell must activate the cell editor.');
newButton = findall(f,'Tag','reflectarrayNew');
newStyle = findall(f,'Tag','reflectarrayPlotStyle');
newAbsoluteDbi = findall(f,'Tag','reflectarrayAbsoluteDbi');
newOverlay = findall(f,'Tag','reflectarrayShowGeometryBeam');
newCutOverlay = findall(f,'Tag','reflectarrayShow3DCut');
newMapMode = findall(f,'Tag','reflectarrayMapMode');
newStyle.Value = 'Cartesian';
newAbsoluteDbi.Value = true;
newOverlay.Value = true;
newCutOverlay.Value = true;
newMapMode.Value = 'Illumination map';
twoDTab = findall(f,'Tag','tab2DPattern');
twoDTab.ButtonPushedFcn(twoDTab,[]);
newButton.ButtonPushedFcn(newButton,[]);
assert(strcmp(newStyle.Value,'Polar') && ~newAbsoluteDbi.Value && ...
    ~newOverlay.Value && ~newCutOverlay.Value && ...
    strcmp(newMapMode.Value,'Phase map') && ...
    strcmp(findall(f,'Tag','viewGeometry').Visible,'on'), ...
    'New must reset view-only controls and return to Geometry.');
assert(strcmp(startupLabel.Text,'No cell selected') && ...
    strcmp(findall(f,'Tag','reflectarraySelectedGeometryCell').Visible,'off') && ...
    strcmp(startupPhase.Enable,'off') && ...
    strcmp(startupMove.Enable,'off') && ...
    strcmp(startupDelete.Enable,'off'), ...
    'New must clear the previous cell selection.');
dxControl = findall(f,'Tag','reflectarrayDxLambda');
dyControl = findall(f,'Tag','reflectarrayDyLambda');
designControl = findall(f,'Tag','reflectarrayDesignFrequency');
operatingControl = findall(f,'Tag','reflectarrayOperatingFrequency');
unitControl = findall(f,'Tag','reflectarrayFrequencyUnit');
fixedPhase = findall(f,'Tag','reflectarrayFixedPhase');
lambdaLabel = findall(f,'Tag','reflectarrayDesignWavelength');
assert(dxControl.Value == 0.5 && dyControl.Value == 0.5 && ...
    designControl.Value == 10 && operatingControl.Value == 10 && ...
    contains(lambdaLabel.Text,'29.98'), ...
    'Design-wavelength spacing and frequency controls did not initialize.');
initialCells = findall(f,'Tag','reflectarrayCells');
initialVertices = initialCells.Vertices;
initialPhaseTable = findall(f,'Tag','reflectarrayPhaseTable');
initialPhases = initialPhaseTable.Data(:,3);
unitControl.Value = 'MHz'; unitControl.ValueChangedFcn(unitControl,[]);
assert(designControl.Value == 10000 && operatingControl.Value == 10000 && ...
    isequal(initialCells.Vertices,initialVertices), ...
    'Changing frequency units must not redesign the surface.');
unitControl.Value = 'GHz'; unitControl.ValueChangedFcn(unitControl,[]);
designControl.Value = 11; designControl.ValueChangedFcn(designControl,[]);
resizedCells = findall(f,'Tag','reflectarrayCells');
assert(~isequal(resizedCells.Vertices,initialVertices) && ...
    dxControl.Value == 0.5, ...
    'Changing design frequency must resize the physical cell pitch.');
designControl.Value = 10; designControl.ValueChangedFcn(designControl,[]);
operatingControl.Value = 12;
operatingControl.ValueChangedFcn(operatingControl,[]);
operatingCells = findall(f,'Tag','reflectarrayCells');
operatingPhaseTable = findall(f,'Tag','reflectarrayPhaseTable');
assert(isequal(operatingCells.Vertices,initialVertices) && ...
    max(abs(operatingPhaseTable.Data(:,3)-initialPhases)) > 1, ...
    'Operating frequency must retune phases without moving cells.');
fixedPhase.Value = true; fixedPhase.ValueChangedFcn(fixedPhase,[]);
fixedPhaseTable = findall(f,'Tag','reflectarrayPhaseTable');
assert(max(abs(fixedPhaseTable.Data(:,3)-initialPhases)) < 0.01, ...
    'Fixed-phase mode must use the design-frequency phase map.');
fixedModel = struct('M',20,'N',20,'dxLambda',0.5,'dyLambda',0.5, ...
    'designFreqGHz',10,'opFreqGHz',12,'retunePhase',false, ...
    'feedMM',[-40 0 120],'feedQ',4,'beamThetaDeg',0, ...
    'beamPhiDeg',0,'shape','Circle','taper','None');
fixedA = reflectarrayAperture(fixedModel);
fixedD = reflectarrayDirectivity(fixedA,fixedA.referencePhaseDeg);
retunedD = reflectarrayDirectivity(fixedA,fixedA.idealPhaseDeg);
expectedFixed = 10*log10(fixedD.factor* ...
    abs(reflectarrayField(fixedA,fixedA.referencePhaseDeg,0,0))^2);
expectedRetuned = 10*log10(retunedD.factor);
absoluteStyle = findall(f,'Tag','reflectarrayPlotStyle');
absoluteDbi = findall(f,'Tag','reflectarrayAbsoluteDbi');
absoluteStyle.Value = 'Cartesian';
absoluteStyle.ValueChangedFcn(absoluteStyle,[]);
absoluteDbi.Value = true; absoluteDbi.ValueChangedFcn(absoluteDbi,[]);
absoluteAxes = findall(f,'Tag','reflectarray2DCartesian');
fixedCurve = findall(absoluteAxes,'Type','Line', ...
    'DisplayName','Assigned phase');
retunedCurve = findall(absoluteAxes,'Type','Line', ...
    'DisplayName','Retuned at operating frequency');
zeroIndex = find(fixedCurve.XData == 0,1);
assert(isscalar(fixedCurve) && isscalar(retunedCurve) && ...
    ~isempty(zeroIndex) && ...
    abs(fixedCurve.YData(zeroIndex)-expectedFixed) < 0.02 && ...
    abs(retunedCurve.YData(zeroIndex)-expectedRetuned) < 0.02, ...
    'Fixed and retuned dBi curves must use separate power normalizations.');
absoluteDbi.Value = false; absoluteDbi.ValueChangedFcn(absoluteDbi,[]);
absoluteStyle.Value = 'Polar'; absoluteStyle.ValueChangedFcn(absoluteStyle,[]);
operatingControl.Value = 10;
operatingControl.ValueChangedFcn(operatingControl,[]);
fixedPhase.Value = false; fixedPhase.ValueChangedFcn(fixedPhase,[]);
assert(isscalar(findall(f,'Tag','reflectarrayGeometryAxes')));
cells = findall(f,'Tag','reflectarrayCells');
assert(isscalar(cells) && ~isempty(cells.Faces), ...
    'The default surface cells did not render.');
firstCell = cells.Vertices(cells.Faces(1,:),:);
normal = cross(firstCell(2,:)-firstCell(1,:), ...
    firstCell(3,:)-firstCell(2,:));
assert(all(firstCell(:,3) == 0) && normal(3) > 0, ...
    'Reflecting cells must lie in the xy plane and face +z.');
assert(~isempty(cells.ButtonDownFcn), ...
    'Geometry cells must respond to clicks.');
geometryAx = findall(f,'Tag','reflectarrayGeometryAxes');
view(geometryAx,55,22);
initialCount = size(cells.Faces,1);
geometryAx.ButtonDownFcn(geometryAx, ...
    struct('IntersectionPoint',[1e6 1e6 0]));
assert(size(findall(f,'Tag','reflectarrayCells').Faces,1) == initialCount, ...
    'Clicking far outside the aperture must not add a cell.');
defaultDxMM = 0.5*299.792458/10;
clickX = 1.5*defaultDxMM;
clickY = -0.5*defaultDxMM;
cells.ButtonDownFcn(cells,struct('IntersectionPoint',[clickX clickY 0]));
selectedLabel = findall(f,'Tag','reflectarraySelectedCellLabel');
selectedOutline = findall(f,'Tag','reflectarraySelectedGeometryCell');
[azimuth,elevation] = view(geometryAx);
assert(contains(selectedLabel.Text,'Cell (10, 12)') && ...
    abs(mean(selectedOutline.Vertices(:,1))-clickX) < 1e-10 && ...
    abs(mean(selectedOutline.Vertices(:,2))-clickY) < 1e-10 && ...
    azimuth == 55 && elevation == 22, ...
    'Clicking a geometry cell must select it without resetting the view.');
mouth = findall(f,'Tag','reflectarrayHornOpening');
assert(numel(findall(f,'Tag','reflectarrayHornSegment')) == 2 && ...
    isscalar(mouth) && isequal(size(mouth.Faces),[4 4]) && ...
    isscalar(findall(f,'Tag','reflectarrayHornInterior')), ...
    'The rectangular horn and its open mouth did not render.');
defaultFeedX = findall(f,'Tag','reflectarrayFeedX');
rearPort = findall(f,'Tag','reflectarrayHornRearPort');
assert(defaultFeedX.Value == -40 && ...
    abs(mean(rearPort.Vertices(:,1))+40) < 1e-10 && ...
    mean(mouth.Vertices(1:4,1)) > -40, ...
    'The default offset horn must sit at x = -40 mm and aim inward.');
overlay = findall(f,'Tag','reflectarrayShowGeometryBeam');
assert(isscalar(overlay) && ~overlay.Value && ...
    isempty(findall(f,'Tag','reflectarrayGeometryBeam')), ...
    'Geometry beam overlay should start hidden.');
overlay.Value = true; overlay.ValueChangedFcn(overlay,[]);
[overlayAz,overlayEl] = view(geometryAx);
geometryBeam = findall(f,'Tag','reflectarrayGeometryBeam');
patternAx = findall(f,'Tag','reflectarray3DAxes');
patternBeam = findall(patternAx,'Type','Surface');
assert(isscalar(geometryBeam) && isscalar(patternBeam) && ...
    isequal(geometryBeam.CData,patternBeam.CData) && ...
    geometryBeam.FaceAlpha == 1 && ...
    strcmp(geometryBeam.PickableParts,'none'), ...
    'Geometry overlay must show the same solid 3D pattern.');
assert(isempty(findall(patternAx,'Tag','reflectarray3DCutTrace')), ...
    'The 3D cut trace must start hidden.');
newCutOverlay.Value = true; newCutOverlay.ValueChangedFcn(newCutOverlay,[]);
cutTrace = findall(patternAx,'Tag','reflectarray3DCutTrace');
assert(isscalar(cutTrace) && max(abs(cutTrace.YData)) < 1e-9, ...
    'The 3D theta-cut trace must lie in the selected phi plane.');
assert(overlayAz == 55 && overlayEl == 22, ...
    'Redrawing the geometry beam must preserve the camera.');
overlay.Value = false; overlay.ValueChangedFcn(overlay,[]);
assert(isempty(findall(f,'Tag','reflectarrayGeometryBeam')), ...
    'Geometry beam overlay did not hide.');
assert(strcmp(findall(f,'Tag','reflectarrayCells').PickableParts,'visible') && ...
    ~isempty(geometryAx.ButtonDownFcn), ...
    'Redrawing geometry must preserve cell selection.');
overlay.Value = false; overlay.ValueChangedFcn(overlay,[]);
assert(isscalar(findall(f,'Tag','reflectarrayPhaseAxes')));
assert(isscalar(findall(f,'Tag','reflectarraySpatialDelayAxes')) && ...
    isscalar(findall(f,'Tag','reflectarrayProgressivePhaseAxes')) && ...
    isscalar(findall(f,'Tag','reflectarrayContinuousPhaseAxes')), ...
    'Phase Map must show all four textbook phase views.');
assert(isscalar(findall(f,'Tag','reflectarray3DAxes')));
assert(isscalar(findall(f,'Tag','reflectarray2DPolar')));
tab = findall(f,'Tag','tabPhaseMap');
tab.ButtonPushedFcn(tab,[]);
assert(strcmp(findall(f,'Tag','viewPhaseMap').Visible,'on'), ...
    'Phase map did not open in the same tool window.');
mapMode = findall(f,'Tag','reflectarrayMapMode');
mapMode.Value = 'Illumination map'; mapMode.ValueChangedFcn(mapMode,[]);
incidentMap = findall(f,'Tag','reflectarrayIlluminationAxes');
apertureMap = findall(f,'Tag','reflectarrayApertureAmplitudeAxes');
incidentImage = findall(incidentMap,'Type','Image');
apertureImage = findall(apertureMap,'Type','Image');
assert(strcmp(findall(f,'Tag','viewPhaseMap').Visible,'on') && ...
    isscalar(incidentImage) && isscalar(apertureImage) && ...
    max(incidentImage.CData(:)) <= 0 && ...
    min(incidentImage.CData(:)) < -0.1 && ...
    isequal(size(apertureImage.CData),[20 20]), ...
    'Illumination view must show horn and aperture amplitudes on the cell grid.');
mapMode.Value = 'Phase map'; mapMode.ValueChangedFcn(mapMode,[]);
table = findall(f,'Tag','reflectarrayPhaseTable');
before = table.Data;
cellRow = find(before(:,1)==4 & before(:,2)==4,1);
event = struct('Indices',[cellRow 3], ...
    'NewData',mod(before(cellRow,3)+90,360));
table.CellEditCallback(table,event);
after = table.Data;
assert(abs(after(cellRow,3)-before(cellRow,3)) > 1, ...
    'Editing a cell did not update its reflection phase.');
assert(contains(findall(f,'Tag','reflectarraySelectedCellLabel').Text, ...
    'Cell (4, 4)'), ...
    'Table edits must select the cell being edited.');
sameSize = findall(f,'Tag','reflectarrayRows');
sameSize.ValueChangedFcn(sameSize,[]);
assert(abs(findall(f,'Tag','reflectarrayPhaseTable').Data(cellRow,3)- ...
    after(cellRow,3)) < 1e-12, ...
    'Repeating the same grid size must not erase manual phases.');
restorePhases = findall(f,'Tag','reflectarrayRestoreSynthesizedPhases');
assert(strcmp(restorePhases.Enable,'on'), ...
    'Manual phase editing should enable phase restoration.');
feedX = findall(f,'Tag','reflectarrayFeedX');
view(patternAx,63,17);
feedX.Value = 25; feedX.ValueChangedFcn(feedX,[]);
assert(abs(feedX.Value-25)<eps, 'Feed relocation failed.');
[patternAz,patternEl] = view(patternAx);
assert(patternAz == 63 && patternEl == 17, ...
    'Recalculating the 3D pattern must preserve its camera.');
style = findall(f,'Tag','reflectarrayPlotStyle');
style.Value = 'Cartesian'; style.ValueChangedFcn(style,[]);
cart = findall(f,'Tag','reflectarray2DCartesian');
polar = findall(f,'Tag','reflectarray2DPolar');
assert(strcmp(cart.Visible,'on') && ...
    isempty(findall(polar,'Type','Line')), ...
    'Cartesian view still contains the old polar curve.');
style.Value = 'Polar'; style.ValueChangedFcn(style,[]);
assert(strcmp(polar.Visible,'on') && ...
    isempty(findall(cart,'Type','Line')), ...
    'Polar view still contains the old Cartesian curve.');
style.Value = 'Cartesian'; style.ValueChangedFcn(style,[]);
cut = findall(f,'Tag','reflectarrayCut');
cut.Value = 'Phi cut'; cut.ValueChangedFcn(cut,[]);
assert(~isempty(cart.Children), 'Azimuth pattern did not render.');
restorePhases.ButtonPushedFcn(restorePhases,[]);
steeringTab = findall(f,'Tag','reflectarrayBeamSection');
steeringTab.ButtonPushedFcn(steeringTab,[]);
steerTheta = findall(f,'Tag','reflectarrayBeamTheta');
steerPhi = findall(f,'Tag','reflectarrayBeamPhi');
cutTheta = findall(f,'Tag','reflectarrayCutTheta');
cutPhi = findall(f,'Tag','reflectarrayCutPhi');
followBeam = findall(f,'Tag','reflectarrayFollowBeamCut');
steerTheta.Value = 25; steerTheta.ValueChangedFcn(steerTheta,[]);
steerPhi.Value = 60; steerPhi.ValueChangedFcn(steerPhi,[]);
assignedCut = findall(cart,'Type','Line', ...
    'DisplayName','Assigned phase');
[~,peakIndex] = max(assignedCut.YData);
assert(followBeam.Value && cutTheta.Value == 25 && ...
    strcmp(cutTheta.Enable,'off') && ...
    abs(assignedCut.XData(peakIndex)-60) <= 1, ...
    'Phi cut must follow the commanded theta and show the steered phi.');
cutTrace = findall(patternAx,'Tag','reflectarray3DCutTrace');
traceTheta = atan2d(hypot(cutTrace.XData,cutTrace.YData), ...
    cutTrace.ZData);
assert(isscalar(cutTrace) && max(abs(traceTheta-25)) < 1e-9, ...
    'The 3D phi-cut trace must follow the selected fixed-theta cone.');
absoluteDbi.Value = true; absoluteDbi.ValueChangedFcn(absoluteDbi,[]);
absoluteCut = findall(cart,'Type','Line','DisplayName','Assigned phase');
statusLabel = findall(f,'Tag','reflectarrayStatus');
targetToken = regexp(statusLabel.Text, ...
    'modeled D toward target (-?[\d.]+) dBi','tokens','once');
atTarget = find(absoluteCut.XData == 60,1);
assert(isscalar(absoluteCut) && ~isempty(targetToken) && ...
    ~isempty(atTarget) && ...
    abs(absoluteCut.YData(atTarget)-str2double(targetToken{1})) < 0.02 && ...
    contains(lower(cart.YLabel.String),'directivity'), ...
    'The dBi cut must agree with the modeled target directivity.');
style.Value = 'Polar'; style.ValueChangedFcn(style,[]);
assert(strcmp(polar.Visible,'on') && ...
    contains(polar.Title.String,'Phi cut'), ...
    'Polar dBi mode must render the absolute directivity scale.');
style.Value = 'Cartesian'; style.ValueChangedFcn(style,[]);
absoluteDbi.Value = false; absoluteDbi.ValueChangedFcn(absoluteDbi,[]);
steerPhi.Value = 120; steerPhi.ValueChangedFcn(steerPhi,[]);
assignedCut = findall(cart,'Type','Line', ...
    'DisplayName','Assigned phase');
[~,peakIndex] = max(assignedCut.YData);
assert(abs(assignedCut.XData(peakIndex)-120) <= 1, ...
    'Changing beam phi must move the peak of the azimuth cut.');
steerPhi.Value = 210; steerPhi.ValueChangedFcn(steerPhi,[]);
assignedCut = findall(cart,'Type','Line', ...
    'DisplayName','Assigned phase');
[~,peakIndex] = max(assignedCut.YData);
assert(abs(assignedCut.XData(peakIndex)-210) <= 1 && ...
    assignedCut.XData(1) == 0 && assignedCut.XData(end) == 360 && ...
    contains(cart.Title.String,'steer φ = 210.0°'), ...
    'The phi plot must use the same 0–360° convention as beam steering.');
followBeam.Value = false; followBeam.ValueChangedFcn(followBeam,[]);
cutTheta.Value = 15; cutTheta.ValueChangedFcn(cutTheta,[]);
steerPhi.Value = 150; steerPhi.ValueChangedFcn(steerPhi,[]);
assert(cutTheta.Value == 15 && strcmp(cutTheta.Enable,'on'), ...
    'Manual azimuth cut theta must remain available when Follow beam is off.');
followBeam.Value = true; followBeam.ValueChangedFcn(followBeam,[]);
cut.Value = 'Theta cut'; cut.ValueChangedFcn(cut,[]);
steerTheta.Value = 25; steerTheta.ValueChangedFcn(steerTheta,[]);
steerPhi.Value = 60; steerPhi.ValueChangedFcn(steerPhi,[]);
assignedCut = findall(cart,'Type','Line','DisplayName','Assigned phase');
followingPhiCurve = assignedCut.YData;
assert(strcmp(cutPhi.Visible,'on') && ...
    strcmp(cutTheta.Visible,'off') && cutPhi.Value == 60 && ...
    strcmp(cutPhi.Enable,'off'), ...
    'Theta cut must show the phi plane and follow beam phi by default.');
followBeam.Value = false; followBeam.ValueChangedFcn(followBeam,[]);
cutPhi.Value = 120; cutPhi.ValueChangedFcn(cutPhi,[]);
assignedCut = findall(cart,'Type','Line','DisplayName','Assigned phase');
assert(strcmp(cutPhi.Enable,'on') && ...
    contains(cart.Title.String,'φ = 120.0°') && ...
    contains(cart.XLabel.String,'φ = 120.0°') && ...
    max(abs(assignedCut.YData-followingPhiCurve)) > 0.1, ...
    'Manual phi must change the theta-cut plane and its plotted field.');
steerPhi.Value = 90; steerPhi.ValueChangedFcn(steerPhi,[]);
assert(cutPhi.Value == 120, ...
    'Manual theta-cut phi must remain fixed when the beam phi changes.');
followBeam.Value = true; followBeam.ValueChangedFcn(followBeam,[]);
assert(cutPhi.Value == 90 && strcmp(cutPhi.Enable,'off'), ...
    'Following the beam must restore the commanded theta-cut phi.');
steerTheta.Value = 0; steerTheta.ValueChangedFcn(steerTheta,[]);
steerPhi.Value = 0; steerPhi.ValueChangedFcn(steerPhi,[]);
assert(isempty(findall(f,'Tag','reflectarrayGeometryEditor')) && ...
    isempty(findall(f,'Tag','reflectarrayCurrentShape')), ...
    'Design should not duplicate the Array Geometry shape selector.');
geometryTab = findall(f,'Tag','reflectarrayArrayGeometrySection');
geometryTab.ButtonPushedFcn(geometryTab,[]);
editor = findall(f,'Tag','reflectarrayArrayGeometryPanel');
gallery = findall(f,'Tag','reflectarrayShapeGallery');
galleryToggle = findall(editor,'Tag','reflectarrayShapeGalleryToggle');
galleryToggle.ButtonPushedFcn(galleryToggle,[]);
assert(isscalar(editor) && strcmp(editor.Visible,'on') && ...
    isscalar(gallery) && strcmp(gallery.Visible,'on') && ...
    isempty(findall(0,'Type','figure','Tag','reflectarraySurfaceEditor')) && ...
    strcmp(findall(f,'Tag','reflectarrayDesignPanel').Visible,'off'), ...
    'Array Geometry gallery must open inside the main window.');
custom = findall(gallery,'Tag','reflectarrayShapeCustom');
custom.ButtonPushedFcn(custom,[]);
preview = findall(editor,'Tag','reflectarrayShapePreview3');
assert(strcmp(gallery.Visible,'off') && strcmp(preview.Text,'Custom') && ...
    isequal(preview.BackgroundColor,[0.17 0.43 0.77]), ...
    'Selecting a gallery tile must update the active preview.');
arrow = findall(editor,'Tag','reflectarrayShapeGalleryToggle');
arrow.ButtonPushedFcn(arrow,[]);
assert(strcmp(gallery.Visible,'on'),'The gallery arrow must expand the shape menu.');
galleryY = gallery.Position(2);
f.WindowState = 'normal';
f.Position = [90 65 1000 700];
drawnow;
assert(gallery.Position(2) < galleryY, ...
    'The shape gallery must follow its selector on window resize.');
arrow.ButtonPushedFcn(arrow,[]);
assert(strcmp(gallery.Visible,'off'),'The gallery arrow must close the shape menu.');
assert(size(findall(f,'Tag','reflectarrayCells').Faces,1) == 400, ...
    'Custom shape should restore the full 20-by-20 surface.');
table = findall(f,'Tag','reflectarrayPhaseTable');
table.CellSelectionCallback(table,struct('Indices',[1 1;2 1]));
selection = findall(f,'Tag','reflectarraySelectedGeometryCell');
assert(size(selection.Faces,1) == 2, ...
    'Selecting two table rows must highlight both cells.');
edited = table.Data;
table.CellEditCallback(table,struct('Indices',[3 3], ...
    'NewData',mod(edited(3,3)+45,360)));
assert(size(findall(f,'Tag','reflectarraySelectedGeometryCell').Faces,1) == 1 && ...
    contains(findall(f,'Tag','reflectarraySelectedCellLabel').Text, ...
    'Cell (1, 3)'), ...
    'Editing a table row must replace stale multi-selection.');
table.CellSelectionCallback(table,struct('Indices',[1 1;2 1]));
circleMask = reflectarrayShapeMask( ...
    meshgrid(-3.5:3.5),repmat((-3.5:3.5).',1,8),'Circle');
ellipseMask = reflectarrayShapeMask( ...
    meshgrid(-3.5:3.5),repmat((-3.5:3.5).',1,8),'Ellipse');
assert(~isequal(circleMask,ellipseMask), ...
    'Circle and Ellipse must produce visibly different cell masks.');
gridAngle = findall(editor,'Tag','reflectarrayGridAngle');
gridAngle.Value = 75; gridAngle.ValueChangedFcn(gridAngle,[]);
stagger = findall(editor,'Tag','reflectarrayRowStagger');
staggerAngle = findall(editor,'Tag','reflectarrayStaggerAngle');
stagger.Value = 0.2; stagger.ValueChangedFcn(stagger,[]);
assert(abs(staggerAngle.Value-atan2d(0.2,0.5)) < 1e-10, ...
    'Stagger angle must track the alternating-row offset.');
staggerAngle.Value = 45; staggerAngle.ValueChangedFcn(staggerAngle,[]);
assert(abs(stagger.Value-0.5) < 1e-10, ...
    'Editing stagger angle must update row stagger.');
skewedVertices = findall(f,'Tag','reflectarrayCells').Vertices;
assert(~isequal(skewedVertices,initialVertices), ...
    'Grid angle must change the cell coordinates.');
beforeMove = findall(f,'Tag','reflectarraySelectedGeometryCell').Vertices;
moveX = findall(editor,'Tag','reflectarrayMoveX');
moveX.Value = 0.2;
move = findall(editor,'Tag','reflectarrayCellAction1');
move.ButtonPushedFcn(move,[]);
afterMove = findall(f,'Tag','reflectarraySelectedGeometryCell').Vertices;
assert(abs(mean(afterMove(:,1))-mean(beforeMove(:,1))-0.2*defaultDxMM/0.5) < 1e-8, ...
    'Moving selected cells by design wavelengths must change physical geometry.');
assert(isempty(findall(f,'Tag','reflectarraySelectedRotation')) && ...
    isempty(findall(f,'Tag','reflectarrayApplySequentialRotation')), ...
    'Drawing-only rotation controls should be absent.');
table = findall(f,'Tag','reflectarrayPhaseTable');
table.CellSelectionCallback(table,struct('Indices',[1 1;2 1]));
deleteButton = findall(editor,'Tag','reflectarrayCellAction3');
restore = findall(editor,'Tag','reflectarrayCellAction5');
multiCount = size(findall(f,'Tag','reflectarrayCells').Faces,1);
deleteButton.ButtonPushedFcn(deleteButton,[]);
assert(size(findall(f,'Tag','reflectarrayCells').Faces,1) == multiCount-2 && ...
    strcmp(restore.Enable,'on'), ...
    'Deleting two selected cells must enable Undo.');
restore.ButtonPushedFcn(restore,[]);
assert(size(findall(f,'Tag','reflectarrayCells').Faces,1) == multiCount && ...
    strcmp(restore.Enable,'off'), ...
    'Undo must restore every cell in the last deletion.');
table.CellSelectionCallback(table,struct('Indices',[10 1]));
countBeforeDelete = size(findall(f,'Tag','reflectarrayCells').Faces,1);
deleteButton.ButtonPushedFcn(deleteButton,[]);
restore.ButtonPushedFcn(restore,[]);
assert(size(findall(f,'Tag','reflectarrayCells').Faces,1) == countBeforeDelete && ...
    contains(findall(f,'Tag','reflectarraySelectedCellLabel').Text, ...
    'Cell (1, 10)'), ...
    'Restore must recover the deleted cell and select it.');
clearButton = findall(editor,'Tag','reflectarrayCellAction4');
clearButton.ButtonPushedFcn(clearButton,[]);
assert(isempty(findall(f,'Tag','reflectarrayCells').Faces) && ...
    contains(findall(f,'Tag','reflectarraySelectedCellLabel').Text,'No active'), ...
    'Clear all must leave an editable empty surface.');
restore = findall(editor,'Tag','reflectarrayCellAction5');
restore.ButtonPushedFcn(restore,[]);
assert(size(findall(f,'Tag','reflectarrayCells').Faces,1) == 400, ...
    'Undo must restore the surface after Clear all.');
assert(size(findall(f,'Tag','reflectarraySelectedGeometryCell').Faces,1) == 1, ...
    'Undo Clear should restore the previous selection, not select every cell.');
designTab = findall(f,'Tag','reflectarrayDesignSection');
designTab.ButtonPushedFcn(designTab,[]);
assert(strcmp(editor.Visible,'off') && ...
    strcmp(findall(f,'Tag','reflectarrayDesignPanel').Visible,'on'), ...
    'Design controls must be reachable without another window.');
beamTab = findall(f,'Tag','reflectarrayBeamSection');
beamTab.ButtonPushedFcn(beamTab,[]);
beamPanel = findall(f,'Tag','reflectarrayBeamPanel');
assert(strcmp(beamPanel.Visible,'on') && ...
    isscalar(findall(beamPanel,'Tag','reflectarrayFeedX')) && ...
    isscalar(findall(beamPanel,'Tag','reflectarrayBeamTheta')), ...
    'Horn location and intended beam must live in the Beam section.');
sourceChoice = findall(beamPanel,'Tag','reflectarrayIlluminationMode');
incidentTheta = findall(beamPanel,'Tag','reflectarrayIncidentTheta');
incidentPhi = findall(beamPanel,'Tag','reflectarrayIncidentPhi');
sourceChoice.Value = 'Plane wave';
sourceChoice.ValueChangedFcn(sourceChoice,[]);
wavefront = findall(f,'Tag','reflectarrayPlaneWavefront');
incomingArrow = findall(f,'Tag','reflectarrayPlaneWaveRay');
assert(isempty(findall(f,'Tag','reflectarrayHornSegment')) && ...
    isscalar(wavefront) && wavefront.FaceColor(1) > wavefront.FaceColor(3) && ...
    isscalar(incomingArrow) && ...
    abs(incomingArrow.ZData-mean(wavefront.Vertices(:,3))) < 1e-10 && ...
    incomingArrow.WData < 0 && incomingArrow.MaxHeadSize < 0.6 && ...
    strcmp(defaultFeedX.Visible,'off') && ...
    strcmp(incidentTheta.Visible,'on') && ...
    contains(geometryAx.Title.String,'Plane-wave'), ...
    'Plane-wave mode must replace the horn with incoming wavefronts.');
incidentTheta.Value = 25;
incidentTheta.ValueChangedFcn(incidentTheta,[]);
incidentPhi.Value = 40;
incidentPhi.ValueChangedFcn(incidentPhi,[]);
assert(isscalar(findall(f,'Tag','reflectarrayPlaneWavefront')) && ...
    isscalar(findall(f,'Tag','reflectarrayPlaneWaveRay')) && ...
    strcmp(findall(f,'Tag','reflectarrayCells').PickableParts,'visible'), ...
    'Changing plane-wave direction must preserve editable surface geometry.');
sourceChoice.Value = 'Horn';
sourceChoice.ValueChangedFcn(sourceChoice,[]);
assert(numel(findall(f,'Tag','reflectarrayHornSegment')) == 2 && ...
    isempty(findall(f,'Tag','reflectarrayPlaneWavefront')) && ...
    strcmp(defaultFeedX.Visible,'on') && ...
    strcmp(incidentTheta.Visible,'off'), ...
    'Switching back to horn mode must restore horn controls and geometry.');
twoDTab.ButtonPushedFcn(twoDTab,[]);
cut.Value = 'Phi cut'; cut.ValueChangedFcn(cut,[]);
drawnow;
cutTools = followBeam.Parent;
fixedWidth = sum(cell2mat(cutTools.ColumnWidth(1:7))) + ...
    7*cutTools.ColumnSpacing;
availableWidth = f.Position(3) - 16 ... % root padding
    - 350 - 8 ... % control panel and body spacing
    - 16; % 2D cut grid padding
assert(availableWidth-fixedWidth >= 100 && ...
    absoluteDbi.Layout.Column == 5 && ...
    cutTheta.Layout.Column == 7 && cutPhi.Layout.Column == 7 && ...
    followBeam.Layout.Column == 8, ...
    'Phi cut controls must fit inside a 1000-pixel window.');
columns = findall(f,'Tag','reflectarrayColumns');
sameSize.Value = 2; columns.Value = 2;
sameSize.ValueChangedFcn(sameSize,[]);
gridAngle.Value = 90; gridAngle.ValueChangedFcn(gridAngle,[]);
stagger.Value = 0; stagger.ValueChangedFcn(stagger,[]);
sourceChoice.Value = 'Plane wave';
sourceChoice.ValueChangedFcn(sourceChoice,[]);
incidentTheta.Value = 0; incidentTheta.ValueChangedFcn(incidentTheta,[]);
incidentPhi.Value = 0; incidentPhi.ValueChangedFcn(incidentPhi,[]);
sweepTab = findall(f,'Tag','tabFrequencySweep');
sweepTab.ButtonPushedFcn(sweepTab,[]);
sweepStart = findall(f,'Tag','reflectarraySweepStart');
sweepStop = findall(f,'Tag','reflectarraySweepStop');
sweepPoints = findall(f,'Tag','reflectarraySweepPoints');
runSweep = findall(f,'Tag','reflectarrayRunSweep');
sweepStart.Value = 9; sweepStart.ValueChangedFcn(sweepStart,[]);
sweepStop.Value = 11; sweepStop.ValueChangedFcn(sweepStop,[]);
sweepPoints.Value = 3; sweepPoints.ValueChangedFcn(sweepPoints,[]);
runSweep.ButtonPushedFcn(runSweep,[]);
sweepAxes = findall(f,'Tag','reflectarraySweepDirectivityAxes');
sweepLines = findall(sweepAxes,'Type','Line', ...
    'DisplayName','Commanded direction');
assert(strcmp(findall(f,'Tag','viewFrequencySweep').Visible,'on') && ...
    isscalar(sweepLines) && numel(sweepLines.XData) == 3 && ...
    max(abs(sweepLines.XData-[9 10 11])) < 1e-12 && ...
    all(isfinite(sweepLines.YData)), ...
    'Run sweep must plot fixed-phase directivity at the chosen frequencies.');
steerTheta.Value = 90; steerTheta.ValueChangedFcn(steerTheta,[]);
assert(isempty(findall(sweepAxes,'Type','Line', ...
    'DisplayName','Commanded direction')), ...
    'Changing the model must invalidate stale sweep results.');
steerPhi.Value = 0; steerPhi.ValueChangedFcn(steerPhi,[]);
followBeam.Value = false; followBeam.ValueChangedFcn(followBeam,[]);
cutTheta.Value = 0; cutTheta.ValueChangedFcn(cutTheta,[]);
style.Value = 'Cartesian'; style.ValueChangedFcn(style,[]);
nullCut = findall(cart,'Type','Line','DisplayName','Assigned phase');
assert(isscalar(nullCut) && max(nullCut.YData) <= -39.9, ...
    'A broadside cut through a 2-by-2 array null must show the plot floor.');
absoluteDbi.Value = true; absoluteDbi.ValueChangedFcn(absoluteDbi,[]);
nullDbiCut = findall(cart,'Type','Line','DisplayName','Assigned phase');
assert(all(isfinite(nullDbiCut.YData)) && ...
    max(nullDbiCut.YData) <= cart.YLim(2)-40.9, ...
    'The dBi view must also show a null at its floor.');
fprintf('Reflectarray core and UI smoke test passed.\n');
end

function deleteExportFiles(csvPath,tsvPath)
if isfile(csvPath), delete(csvPath); end
if isfile(tsvPath), delete(tsvPath); end
end

function rejected = rejectsProject(P)
rejected = false;
try
    reflectarrayValidateProject(P);
catch err
    rejected = startsWith(err.identifier,'Reflectarray:');
end
end

function rejected = rejectsCalculation(callback)
rejected = false;
try
    callback();
catch err
    rejected = startsWith(err.identifier,'Reflectarray:');
end
end
